import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import {hasLocale, NextIntlClientProvider} from "next-intl";
import {routing} from "@/i18n/routing";
import {notFound} from "next/navigation";
import {getMessages, setRequestLocale} from "next-intl/server";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Project Template",
    description: "Generated by create next app",
};

type Props = {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
};

export function generateStaticParams() {
    return routing.locales.map(locale => ({locale}));
}

export default async function RootLayout({children, params}: Props) {
    const {locale} = await params;

    if (!hasLocale(routing.locales, locale)) return notFound();

    setRequestLocale(locale);

    const messages = await getMessages();

    const themeScript = `
      (function() {
        var theme = localStorage.getItem('theme');
        if (theme !== 'light') {
          document.documentElement.classList.add('dark');
        }
      })();
    `;

    return (
        <html lang={locale} suppressHydrationWarning>
        <head>
            <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextIntlClientProvider messages={messages}>
            {children}
        </NextIntlClientProvider>
        </body>
        </html>
    );
}
