import type {Metadata} from "next";
import "./globals.css";
import {hasLocale, NextIntlClientProvider} from "next-intl";
import {routing} from "@/i18n/routing";
import {notFound} from "next/navigation";
import {getMessages, setRequestLocale} from "next-intl/server";
import {Providers} from "@/components/Providers";

export const metadata: Metadata = {
    title: "Project Template",
    description: "Generated by create next app",
};

type Props = {
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
};

export function generateStaticParams() {
    return routing.locales.map(locale => ({locale}));
}

export default async function RootLayout({children, params}: Props) {
    const {locale} = await params;

    if (!hasLocale(routing.locales, locale)) return notFound();

    setRequestLocale(locale);

    const messages = await getMessages();

    const themeScript = `
      (function() {
        var theme = localStorage.getItem('theme');
        if (theme !== 'light') {
          document.documentElement.classList.add('dark');
        }
      })();
    `;

    return (
        <html lang={locale} suppressHydrationWarning>
        <head>
            <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        </head>
        <body className="font-sans antialiased">
        <Providers>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </Providers>
        </body>
        </html>
    );
}
